apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app-deploy
  labels:
    app: hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  hello-world-app
  template:
    metadata:
      labels:
        app:  hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: yuyatinnefeld/hello-world:1.2.0
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE
              value: "Message_from_K8S"
            - name: VERSION
              value: "1.2.0"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app:  hello-world-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http-hello-world
  type: LoadBalancer