apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app-deploy
  labels:
    app: hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  hello-world-app
  template:
    metadata:
      labels:
        app:  hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: yuyatinnefeldcontainerregistry/hello-world:1.3.0
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE
              value: "MY_K8S_MESSAGE"
            - name: VERSION
              value: "1.3.0"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app:  hello-world-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http-hello-world
  type: LoadBalancer